baseurl = "https://codebushi.com/"
languageCode = "en-us"
title = "Code Bushi"
theme = "gohugo-amp"
enableRobotsTXT = false
publishDir = "amp"

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.7

[params]
    amp = true
    ampElements = ["amp-analytics"]
    themeColor = "#f72060"
    googleAnalytics = "UA-115990515-1"
    ampManifest = "/amp-manifest.json"
    alternatePageName = "Code Bushi"
    author = "Hunter Chang"
    organizationLogo = "https://codebushi.com/codebushilogo.png"
    organizationName = "codebushi.com"
    publisherName = "codebushi.com"
    publisherLogo = "https://codebushi.com/codebushilogoamp.png"
    publisherLogoWidth = 320
    publisherLogoHeight = 60
    stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
    javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page
